name: cool_magic
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^7.2.1
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  font_awesome_flutter: ^9.2.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  google_fonts: ^2.1.0
  meta: ^1.7.0
  very_good_analysis: ^2.4.0

dev_dependencies:
  bloc_test: ^8.4.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
